version: '3.8'

services:
  localstack:
    image: localstack/localstack:2.0.1
    ports:
      - 4566:4566
    environment:
      - SERVICES=S3,lambda
    networks:
      - network1

  producer:
    tty: true
    volumes:
      - ./:/mount
    build:
      context: .
    networks:
      - network1
    ports:
      - 8080:8080

volumes:
  localstack:
    name: localstack-volumes
    driver: local

networks:
  network1:
    name: network1
    external: true
